/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cloud/elephant.glb 
*/

import React, { useRef } from "react"
import { useGLTF, useAnimations } from "@react-three/drei"

export function Model(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF(
    "./models/elephant/elephant.glb"
  )
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group
          name="Armature"
          position={[-0.035, 0.257, -0.35]}
          rotation={[1.494, 0, 0]}
        >
          <primitive object={nodes.Bone} />
          <primitive object={nodes.Bone001} />
          <primitive object={nodes.Bone004} />
          <primitive object={nodes.Bone013} />
          <primitive object={nodes.neutral_bone} />
          <skinnedMesh
            name="Elephant"
            geometry={nodes.Elephant.geometry}
            material={nodes.Elephant.material}
            skeleton={nodes.Elephant.skeleton}
          />
        </group>
        <mesh
          name="11"
          geometry={nodes["11"].geometry}
          material={nodes["11"].material}
          position={[-0.024, 0.778, 0.217]}
          rotation={[Math.PI / 2, 0, 0]}
        />
        <mesh
          name="16"
          geometry={nodes["16"].geometry}
          material={nodes["16"].material}
          position={[-0.024, 0.65, 0.217]}
          rotation={[Math.PI / 2, 0, 0]}
        />
      </group>
    </group>
  )
}

useGLTF.preload("./models/elephant/elephant.glb")
