/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/cloud/model.glb 
*/
import * as THREE from "three"
import { useGLTF } from "@react-three/drei"

export function Cloud({ opacity, ...props }) {
  const { nodes, materials } = useGLTF("./models/cloud/clouded.glb")

  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.cloudball001.geometry}>
        <meshStandardMaterial
          material={nodes.cloudball001.material}
          color="#ffffff"
          // emissive={"#6868ff"}
          // emissiveIntensity={0.2}
          transparent
          opacity={opacity}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload("./models/cloud/clouded.glb")
