/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/airplane/planeur.glb 
*/

import React, { useRef } from "react"
import { useGLTF } from "@react-three/drei"
import * as THREE from "three"

export function Plane(props) {
  const { nodes, materials } = useGLTF("./models/airplane/planeur.glb")

  if (!nodes.Cylinder) return null

  nodes.Cylinder.material.emissive = new THREE.Color("#6868ff")
  nodes.Cylinder.material.emissiveIntensity = 0.5
  nodes.Cylinder.material.metalness = 1
  nodes.Cylinder.material.roughness = 0.9

  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={nodes.Cylinder.material}
      />
    </group>
  )
}

useGLTF.preload("./models/airplane/planeur.glb")
